In [1]:
# Feature selection :
# it is done to remove unnecessary features in the data for the following benefits:
# Reduce-Over fitting: Reduces Over Fitting
# Improve Accuracy
# reduce training time by reducing the computational complexity

# Feature Selection can be done in 4 ways

# Univariate selection using the statistical tests like chi2 on non negative attribute
# Recursive Feature Elimination
# Principal Component Analysis
# Feature Importance

In [17]:
# feature selection using the Univariate selection and chi2 statistical method
import pandas as pd
import numpy as np
import sklearn 
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import *
df = pd.read_csv('C:\\Users\\vardh\\Vardhan\\ED\\diabetes.csv')
X = df.iloc[:,0:8]
Y = df.iloc[:,8]
skb = SelectKBest(score_func=chi2,k=4)
fit = skb.fit(X,Y)
print(fit.scores_)
td1 = fit.transform(X)
td1

[ 111.51969064 1411.88704064   17.60537322   53.10803984 2175.56527292
  127.66934333    5.39268155  181.30368904]


array([[148. ,   0. ,  33.6,  50. ],
       [ 85. ,   0. ,  26.6,  31. ],
       [183. ,   0. ,  23.3,  32. ],
       ...,
       [121. , 112. ,  26.2,  30. ],
       [126. ,   0. ,  30.1,  47. ],
       [ 93. ,   0. ,  30.4,  23. ]])

In [27]:
# Feature selection using the Recursive Feature Elimination
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
rfe = RFE(LR,n_features_to_select=4)
fit = rfe.fit(X,Y)
print(fit.support_,fit.ranking_)
td1 = fit.transform(X)
td1

[ True  True False False False  True  True False] [1 1 2 4 5 1 1 3]


c:\users\vardh\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\vardh\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\vardh\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\vardh\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\vardh\appdata\local\programs\python\python37\lib\si

array([[  6.   , 148.   ,  33.6  ,   0.627],
       [  1.   ,  85.   ,  26.6  ,   0.351],
       [  8.   , 183.   ,  23.3  ,   0.672],
       ...,
       [  5.   , 121.   ,  26.2  ,   0.245],
       [  1.   , 126.   ,  30.1  ,   0.349],
       [  1.   ,  93.   ,  30.4  ,   0.315]])

In [31]:
#feature selection using Principal Component Analysis (PCA)
# uses linear algebra to compress the dataset called as data reduction

from sklearn.decomposition import PCA
pca = PCA(n_components=4,)
fit = pca.fit(X)
print(fit.explained_variance_ratio_)
print(fit.components_)

[0.88854663 0.06159078 0.02579012 0.01308614]
[[-2.02176587e-03  9.78115765e-02  1.60930503e-02  6.07566861e-02
   9.93110844e-01  1.40108085e-02  5.37167919e-04 -3.56474430e-03]
 [-2.26488861e-02 -9.72210040e-01 -1.41909330e-01  5.78614699e-02
   9.46266913e-02 -4.69729766e-02 -8.16804621e-04 -1.40168181e-01]
 [-2.24649003e-02  1.43428710e-01 -9.22467192e-01 -3.07013055e-01
   2.09773019e-02 -1.32444542e-01 -6.39983017e-04 -1.25454310e-01]
 [-4.90459604e-02  1.19830016e-01 -2.62742788e-01  8.84369380e-01
  -6.55503615e-02  1.92801728e-01  2.69908637e-03 -3.01024330e-01]]


In [43]:
# Feature Importance uses ensembles like ExtraTreeClassifier 
from sklearn.ensemble import ExtraTreesClassifier
etc = ExtraTreesClassifier(n_estimators=10)
fit = etc.fit(X,Y)
print(fit.feature_importances_)

[0.11323659 0.21123399 0.11144455 0.08518482 0.07611967 0.1391022
 0.11314458 0.15053359]
