In [1]:
# pre processing is done to prepare the data before feeding it into the algorithm

#types of preprocessing
# 1. Rescaling
# 2. Standardizing
# 3. Normalizing
# 4. Binarizing

# Fit and Transform = 'The input data is fitted with preprocesssing  method and then transformed'

# it is done to transform the data to suit the working of the algorithm
# ex: resclaing is done to  prepare the data between(0,1) of different scales
#     for gradient descent algorithms, regression, neural netwrok and KNN
# standardizing converts the data into normal (mean =0 and std.dev=1)
# normalizer converts the row (atleast one non zero into unit norm (sum of squares in row =1))
# Binarizer converts the data into binary(0,1) w.r.t to threshold used for feature engieering  

In [12]:
# rescaling the data
import pandas as pd
import numpy as np
import sklearn 
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
df = pd.read_csv('C:\\Users\\vardh\\Vardhan\\ED\\diabetes.csv')
X = df.iloc[:,0:8]
Y = df.iloc[:,8]
sc = MinMaxScaler()
transformed_data = sc.fit_transform(X)
print(transformed_data)

[[0.35294118 0.74371859 0.59016393 ... 0.50074516 0.23441503 0.48333333]
 [0.05882353 0.42713568 0.54098361 ... 0.39642325 0.11656704 0.16666667]
 [0.47058824 0.91959799 0.52459016 ... 0.34724292 0.25362938 0.18333333]
 ...
 [0.29411765 0.6080402  0.59016393 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.49180328 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.57377049 ... 0.45305514 0.10119556 0.03333333]]


In [37]:
#Standardizing the data (each attribute has mean = 0 and std.dev = 1)
from sklearn.preprocessing import StandardScaler
SS = StandardScaler()
td = SS.fit_transform(X)
print(td)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]


In [1]:
#Normalize theinput data (to unit norm (sum squares in each row equals 1))
from sklearn.preprocessing import Normalizer
N = Normalizer()
td1 = N.fit_transform(X)
print(td1)

NameError: name 'X' is not defined

In [53]:
# Binarizer creates binary values wrt a threshold
from sklearn.preprocessing import Binarizer
B = Binarizer()
td2 = B.fit_transform(X)
td2[0:5,:]

array([[1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1.]])